<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../NordicFlow.Application/NordicFlow.Application.csproj" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
